---
#- name: debug test hostvars
#  debug:
#    #msg: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item]['ansible_hostname'] }}"
#    #ansible_hostname != hostvars[ansible_play_batch[0]].ansible_hostname
#    msg: "{{ hostvars[item].ansible_default_ipv4.address }}"
#  with_items: "{{ ansible_play_batch }}"

- name: config hosts
  become: yes
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item]['ansible_hostname'] }}"
  with_items: "{{ ansible_play_batch }}"
