---
# Install required packages

- name: install required packages
  become: true
  yum:
    update_cache: yes
    pkg: "{{ item }}"
    state: present
  with_items:
    - rabbitmq-server

- name: customize logrotate rules
  become: true
  template:
    src: etc/logrotate.d/rabbitmq-server.j2
    dest: /etc/logrotate.d/rabbitmq-servero
    owner: root
    group: root
    mode: 0644
